# Generated by Django 5.1.7 on 2025-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answers_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='answers_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='answers_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_lesson_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_lesson_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_lesson_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
