# Generated by Django 5.1.7 on 2025-03-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_answers_answers_en_answers_answers_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher'},
        ),
    ]
