# Generated by Django 5.1.7 on 2025-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('клиент', 'клиент'), ('преподователь', 'преподователь'), ('администиратор', 'администиратор')], default='клиент', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('клиент', 'клиент'), ('преподователь', 'преподователь'), ('администиратор', 'администиратор')], default='преподователь', max_length=25),
        ),
    ]
