# Generated by Django 5.1.7 on 2025-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_student_role_alter_teacher_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='role',
            new_name='student_role',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='role',
            new_name='teacher_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('клиент', 'клиент'), ('преподователь', 'преподователь'), ('администиратор', 'администиратор')], default='клиент', max_length=25),
        ),
    ]
